base/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetDoneView, PasswordResetCompleteView, \
    LogoutView
from django.urls import path
from . import views
from .views import UserRegistrationView, UserLoginView, UserPasswordChangeView, UserPasswordResetView, \
    UserPasswrodResetConfirmView, ClienteListView, ClienteCreateView, ClienteUpdateView, \
    ClienteDeleteView, CrearOrden, DetalleOrden, EditarOrden, EliminarOrden, \
    contact, EditarPresupuesto, AprobacionExitosaView, RechazoExitosoView, planificacion, \
    asignar_tecnico, get_planificacion_data, manejar_orden, obtener_tiempo_total, actualizar_item, obtener_estado_orden, \
    get_estado_orden, CrearAuto, load_auto, dashboard_tecnico, metricas, UserLogoutView, EditarAuto, \
    obtener_ordenes_del_dia, horas_vendidas, establecer_objetivo_mensual, visualizar_presupuesto, cambiar_estado, \
    ordenes_entregadas

urlpatterns = [
    path('', views.index, name='index'),


    path('accounts/register/', UserRegistrationView.as_view(), name='register'),
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),

    path('accounts/password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change-done/', PasswordChangeDoneView.as_view(
        template_name='accounts/auth-password-change-done.html'
    ), name="password_change_done"),

    path('accounts/password-reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/',
         UserPasswrodResetConfirmView.as_view(), name="password_reset_confirm"
         ),
    path('accounts/password-reset-done/', PasswordResetDoneView.as_view(
        template_name='accounts/auth-password-reset-done.html'
    ), name='password_reset_done'),
    path('accounts/password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='accounts/auth-password-reset-complete.html'
    ), name='password_reset_complete'),

    path('clientes', ClienteListView.as_view(), name='lista_clientes'),
    path('clientes/crear', ClienteCreateView.as_view(), name='crear_cliente'),
    path('clientes/editar/<int:pk>/', ClienteUpdateView.as_view(), name='editar_cliente'),
    path('clientes/eliminar/<int:pk>/', ClienteDeleteView.as_view(), name='eliminar_cliente'),
    path('load-clientes/', views.load_clientes, name='load-clientes'),


    path('dashboard/', dashboard_tecnico, name='dashboard_tecnico'),

    path('orden/<int:pk>', DetalleOrden.as_view(), name='orden'),
    path('crear-orden/', CrearOrden.as_view(), name='crear-orden'),
    path('editar-orden/<int:pk>', EditarOrden.as_view(), name='editar-orden'),
    path('eliminar-orden/<int:pk>', EliminarOrden.as_view(), name='eliminar-orden'),
    path('auto/<int:auto_id>/historial/', views.historial_ordenes_auto, name='historial_ordenes_auto'),
    path('save_intervencion/', DetalleOrden.as_view(), name='save_intervencion'),
    path('delete_intervencion/', DetalleOrden.as_view(), name='delete_intervencion'),
    path('cambiar_estado/', cambiar_estado, name='cambiar_estado'),
    path('ordenes_entregadas/', ordenes_entregadas, name='ordenes_entregadas'),

    path('crear_presupuesto/<int:orden_id>/', views.crear_presupuesto, name='crear-presupuesto'),
    path('editar-presupuesto/<int:pk>', EditarPresupuesto.as_view(), name='editar-presupuesto'),
    path('presupuestos/', views.listar_presupuestos, name='listar_presupuestos'),
    path('presupuesto/<int:presupuesto_id>/', visualizar_presupuesto, name='visualizar_presupuesto'),

    path('contact', contact, name='contact'),

    path('aprobar-presupuesto/<int:presupuesto_id>/<str:token>/', views.aprobar_presupuesto, name='aprobar_presupuesto'),

    path('rechazar-presupuesto/<int:presupuesto_id>/<str:token>/', views.rechazar_presupuesto, name='rechazar_presupuesto'),
    path('aprobacion-exitosa/<int:presupuesto_id>/', AprobacionExitosaView.as_view(), name='aprobacion_exitosa'),
    path('rechazo-exitoso/<int:presupuesto_id>/', RechazoExitosoView.as_view(), name='rechazo_exitoso'),

    path('planificacion/', planificacion, name='planificacion'),
    path('asignar_tecnico/', views.asignar_tecnico, name='asignar_tecnico'),
    path('buscar-tecnico/', views.buscar_tecnico, name='buscar_tecnico'),
    path('get_planificacion_data/', get_planificacion_data, name='get_planificacion_data'),
    path('orden/<int:orden_id>/', manejar_orden, name='manejar_orden'),
    path('orden/<int:orden_id>/tiempo-total/', obtener_tiempo_total, name='get_tiempo_total'),
    path('get_estado_orden/<int:orden_id>/', get_estado_orden, name='get_estado_orden'),
    path('actualizar_item/', actualizar_item, name='actualizar_item'),
    path('obtener_estado_orden/<int:orden_id>/', obtener_estado_orden, name='obtener_estado_orden'),

    path('crear_auto/', CrearAuto.as_view(), name='crear_auto'),
    path('auto/editar/<int:pk>/', EditarAuto.as_view(), name='editar_auto'),

    path('load-auto/', load_auto, name='load-auto'),

    path('metricas/', metricas, name='metricas'),
    path('ordenes-del-dia/', obtener_ordenes_del_dia, name='ordenes_del_dia'),
    path('horas-vendidas/', horas_vendidas, name='horas_vendidas'),
    path('establecer_objetivo_mensual/', establecer_objetivo_mensual, name='establecer_objetivo'),






]

proyecto/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),


]

base/models.py
from datetime import timedelta

from dateutil.relativedelta import relativedelta
from django.db import models, transaction
from django.contrib.auth.models import User
from datetime import timedelta

from django.db.models import Sum
from django.forms import forms, inlineformset_factory
from django.utils import timezone
from .choices import MODELO_VEHICULO, ESTADO_ORDEN, ESTADO_PRESUPUESTO


class Tecnico(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Otros campos específicos para técnicos

    def __str__(self):
        return f'Técnico: {self.user.username}'

class Recepcionista(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Otros campos específicos para recepcionistas

    def __str__(self):
        return f'Recepcionista: {self.user.username}'

class Planificador(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Otros campos específicos para planificadores

    def __str__(self):
        return f'Planificador: {self.user.username}'

def get_user_role(user):
    if hasattr(user, 'tecnico'):
        return 'tecnico'
    elif hasattr(user, 'recepcionista'):
        return 'recepcionista'
    elif hasattr(user, 'planificador'):
        return 'planificador'
    return 'ninguno'

User.get_role = property(get_user_role)


class Cliente(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE,
                                null=True,
                                blank=True)
    nombre = models.CharField(max_length=15)
    apellido = models.CharField(max_length=15)
    dni = models.CharField(max_length=15, unique=True)
    telefono = models.CharField(max_length=15, unique=True)
    email = models.EmailField(max_length=30, unique=True)
    direccion = models.CharField(max_length=15)

    vehiculo = models.CharField(choices=MODELO_VEHICULO, null=False, blank=False, max_length=20, default='seleccione '
                                                                                                         'un modelo')
    provincia = models.CharField(max_length=15, null=True, blank=True)
    localidad = models.CharField(max_length=15, null=True, blank=True)


    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

    def __str__(self):
        return f'{self.nombre} - {self.apellido}'



class Auto(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, related_name='autos')
    matricula = models.CharField(max_length=15, unique=True)  # Asegurarse de que la matrícula sea única
    vehiculo = models.CharField(choices=MODELO_VEHICULO, max_length=20, default='seleccione un modelo')
    chasis = models.CharField(max_length=16, unique=True)
    anio = models.IntegerField(null=True, blank=True)

    class Meta:
        verbose_name = 'Auto'
        verbose_name_plural = 'Autos'

    def __str__(self):
        return f'{self.matricula}'







class Orden(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    id = models.AutoField(primary_key=True)
    intervencion = models.TextField(blank=True, null=True)

    modifacado = models.DateTimeField(auto_now=True)
    entrega = models.DateTimeField(auto_now_add=False, default=None, null=True, blank=True)
    mano_de_obra = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    estado = models.CharField(choices=ESTADO_ORDEN, null=False, blank=False, max_length=20, default='pendiente')
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_inicio = models.DateTimeField(null=True, blank=True)
    fecha_finalizacion = models.DateTimeField(null=True, blank=True)

    km = models.IntegerField(null=True, blank=True)

    tecnico = models.ForeignKey(Tecnico, on_delete=models.SET_NULL, null=True, blank=True)
    hora_asignada = models.TimeField(null=True, blank=True)

    hora_inicio = models.DateTimeField(null=True, blank=True)
    hora_final = models.DateTimeField(null=True, blank=True)
    tiempo_total = models.DurationField(null=True, blank=True, default=timedelta)
    timer_running = models.BooleanField(default=False)
    progreso = models.FloatField(default=0)
    auto = models.ForeignKey(Auto, on_delete=models.CASCADE, null=True, blank=True)  # Cambio aquí


    def iniciar_temporizador(self):
        if not self.timer_running:
            self.hora_inicio = timezone.now()
            self.estado = 'en proceso'
            self.timer_running = True
            self.save()
            print(f'Temporizador iniciado en {self.hora_inicio}')

    def pausar_temporizador(self):
        if self.timer_running:
            tiempo_transcurrido = timezone.now() - self.hora_inicio
            self.tiempo_total += tiempo_transcurrido
            self.timer_running = False
            self.save()

    def detener_temporizador(self):
        if self.timer_running:
            tiempo_transcurrido = timezone.now() - self.hora_inicio
            self.tiempo_total += tiempo_transcurrido
            self.hora_final = timezone.now()
            self.timer_running = False
            self.estado = 'detenido'
            self.save()

    def finalizar_orden(self):
        if not self.timer_running:
            self.estado = 'finalizado'
            self.fecha_finalizacion = timezone.now()  # Establecer la fecha de finalización
            self.save()
            print(f'Orden finalizada. Estado cambiado a {self.estado}')

            # Actualizar horas vendidas por mes
            if self.mano_de_obra:
                año = self.fecha_finalizacion.year  # Utilizar la fecha de finalización
                mes = self.fecha_finalizacion.month
                with transaction.atomic():
                    horas_registradas, created = HorasVendidasPorMes.objects.get_or_create(año=año, mes=mes)
                    horas_registradas.horas_totales += self.mano_de_obra
                    horas_registradas.save()
                    print(f'Horas vendidas actualizadas: {horas_registradas.horas_totales}')




    def get_tecnico_photo_url(self):
        if self.tecnico and self.tecnico.user and self.tecnico.user.profile.photo:
            return self.tecnico.user.profile.photo.url
        return None

    class Meta:
        verbose_name = 'Orden'
        verbose_name_plural = 'Ordenes'

    def __str__(self):
        return f'{self.auto}'


class ItemSolicitado(models.Model):
    orden = models.ForeignKey(Orden, on_delete=models.CASCADE, related_name='items')
    realizado = models.BooleanField(default=False)
    descripcion = models.CharField(max_length=255)




class Presupuesto(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE,
                                null=True,
                                blank=True)
    orden = models.ForeignKey(Orden, on_delete=models.CASCADE, null=True, blank=True)

    id = models.AutoField(primary_key=True)
    detalle = models.TextField(null=True, )
    precio = models.DecimalField(max_digits=20, decimal_places=4, null=True, blank=True)
    estado_presupuesto = models.CharField(choices=ESTADO_PRESUPUESTO, null=False, blank=False, max_length=20,
                                          default='pendiente de envio')
    repuestos = models.TextField(null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    token = models.CharField(max_length=255, blank=True, null=True)
    token_rechazo = models.CharField(max_length=255, blank=True, null=True)
    mano_de_obra_presupuesto = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)



    def __str__(self):
        return f'{self.orden}'


class HorasVendidasPorMes(models.Model):
    año = models.IntegerField()
    mes = models.IntegerField()
    horas_totales = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    objetivo_mensual = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    class Meta:
        unique_together = ('año', 'mes')
        verbose_name = 'Horas Vendidas por Mes'
        verbose_name_plural = 'Horas Vendidas por Mes'

    def __str__(self):
        return  f"{self.mes}/{self.año} - {self.horas_totales} horas"

base/templates/orden/crear_orden.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

base/templates/orden/historial_ordenes_auto.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %} <!-- Asegúrate de cargar el filtro personalizado -->
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Historial de Órdenes de {{ auto.matricula }}</title>
</head>
<body>
    <h1>Historial de Órdenes para el Auto: {{ auto.matricula }}</h1>

    {% if ordenes %}
    <table id="historial-ordenes" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>ID Orden</th>
                <th>Recepcionista</th>
                <th>Tecnico</th>
                <th>Fecha de Creación</th>
                <th>Fecha de Entrega</th>
                <th>Ítems Solicitados</th> <!-- Nueva columna para los ítems solicitados -->
                <th>Acciones</th> <!-- Columna para acciones -->
            </tr>
        </thead>
        <tbody>
            {% for orden in ordenes %}
            <tr>
                <td>{{ orden.id }}</td>
                <td>{{orden.usuario}}</td>
                <td>{{ orden.tecnico }}</td>
                <td>{{ orden.fecha_creacion }}</td>
                <td>{{ orden.entrega }}</td>
                <td>
                    {% if items_por_orden|dictkey:orden.id %}
                        <ul>
                        {% for item in items_por_orden|dictkey:orden.id %}
                            <li>
                                {{ item.descripcion }} - {{ item.cantidad }} - {{ item.realizado|yesno:"Realizado,Pendiente" }}
                            </li>
                        {% endfor %}
                        </ul>
                    {% else %}
                        <p>No hay ítems solicitados para esta orden.</p>
                    {% endif %}
                </td>
                <td>
                    <a class="dropdown-item" href="{% url 'orden' orden.id %}" >Visualizar</a>


                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No hay órdenes asociadas con este auto.</p>
    {% endif %}
</body>

<a href="{% url 'index' %}" class="btn btn-primary">&#x1F860; Volver</a>
{% endblock %}

base/templates/orden/listar_orden.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

base/templates/orden/orden_confirm_delete.html
{% extends "base.html" %}

{%load static%}

{% block breadcrumbs %}{% endblock breadcrumbs %}





{% block content %}

<div class="row">
    <a href="{% url 'index' %}">&#x1F860; Volver</a>
</div>

<div class="cuerpo-tarjeta">
    <form method="POST">
    {% csrf_token %}
    <p>Vas a eliminar esta tarea: "{{orden}}"</p>
    <input class='boton' type="submit" value="Eliminar">
</form>
</div>

{% endblock content %}

base/templates/orden/orden_form.html
{% extends "base.html" %}
{% load static %}

{% block breadcrumbs %}{% endblock breadcrumbs %}
{% block content %}
<!-- Include jQuery from CDN -->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<!-- Include Select2 CSS and JS files -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5>ORDEN DE REPARACIÓN</h5>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}



                        <h3>Ítems Solicitados</h3>
                        {{ items_formset.management_form }}

                        <div id="formset-container">
                            {% for form in items_formset %}
                                <div class="formset-row mb-3 p-3 border rounded">
                                    {{ form.as_p }}
                                    <button type="button" class="remove-item btn btn-danger btn-sm">Eliminar</button>
                                </div>
                            {% endfor %}
                        </div>

                        <button type="button" id="add-item" class="btn btn-primary">Agregar Ítem</button>

                        <!-- Campo oculto para TOTAL_FORMS -->
                        <input type="hidden" name="items-TOTAL_FORMS" id="id_form-TOTAL_FORMS" value="{{ items_formset.total_form_count }}">

                        <!-- Plantilla de formulario vacío -->
                        <div id="empty-form" style="display: none;">
                            <div class="form-group">
                                <label for="id_items-__prefix__-descripcion">Descripción:</label>
                                <input type="text" name="items-__prefix__-descripcion" class="form-control" maxlength="255" id="id_items-__prefix__-descripcion">
                            </div>

                            <div class="form-group">
                                <input type="hidden" name="items-__prefix__-id" id="id_items-__prefix__-id">
                                <input type="hidden" name="items-__prefix__-orden" id="id_items-__prefix__-orden">
                            </div>
                        </div>

                        <div class="form-group mt-3">
                            <input type="submit" class="btn btn-primary" value="Guardar">
                            <a href="{% url 'index' %}" class="btn btn-secondary">&#x1F860; Volver</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-4 mt-3">

            <div id="autoInfo">
                <h4>Información del Vehiculo</h4>
                <p>Chasis: <span id="infoChasis">No disponible</span></p>
                <p>Modelo: <span id="infoVehiculo">No disponible</span></p>
                <p>Año: <span id="infoAno">No disponible</span></p>
                <p>Matrícula: <span id="infoMatricula">No disponible</span></p>
              <a href="#" id="editAuto" data-auto-id="{{ auto.id }}" class="btn btn-secondary" style="display: none;" onclick="redirectToEditPage()">Editar</a>



            </div>
            <div id="clienteInfo" class="mt-3">
                <h4>Información del Cliente</h4>
                <p>Nombre: <span id="infoNombre">No disponible</span></p>
                <p>Apellido: <span id="infoApellido">No disponible</span></p>
                <p>Dni/Cuit: <span id="infoDni">No disponible</span></p>
                <p>Dirección: <span id="infoDireccion">No disponible</span></p>
                <p>Teléfono: <span id="infoTelefono">No disponible</span></p>
                <p>Email: <span id="infoEmail">No disponible</span></p>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    function initializeSelect2() {
        let clienteInfoContainer = $("#clienteInfo");
        let autoInfoContainer = $("#autoInfo");
        let select2AutoInput = $('#id_auto');
        let editAutoLink = $('#editAuto');

        // Initialize select2 for autos
        select2AutoInput.select2({
            ajax: {
                url: '{% url "load-auto" %}',
                dataType: 'json',
                delay: 250,
                data: function (params) {
                    return { term: params.term };
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.error("Error al cargar datos: ", textStatus, errorThrown);
                },
                minimumInputLength: 2
            }
        });

        // Event listener for the select2:select event for autos
        select2AutoInput.on('select2:select', function (e) {
            let auto = e.params.data;
            if (auto) {
                autoInfoContainer.find("#infoChasis").text(auto.chasis || 'No disponible');
                autoInfoContainer.find("#infoVehiculo").text(auto.vehiculo || 'No disponible');
                autoInfoContainer.find("#infoAno").text(auto.anio || 'No disponible');
                autoInfoContainer.find("#infoMatricula").text(auto.matricula || 'No disponible');

                clienteInfoContainer.find("#infoNombre").text(auto.cliente_nombre || 'No disponible');
                clienteInfoContainer.find("#infoApellido").text(auto.cliente_apellido || 'No disponible');
                clienteInfoContainer.find("#infoDni").text(auto.cliente_dni || 'No disponible');
                clienteInfoContainer.find("#infoDireccion").text(auto.cliente_direccion || 'No disponible');
                clienteInfoContainer.find("#infoTelefono").text(auto.cliente_telefono || 'No disponible');
                clienteInfoContainer.find("#infoEmail").text(auto.cliente_email || 'No disponible');

                // Update edit link URL
                editAutoLink.attr('href', '{% url "editar_auto" 0 %}'.replace('0', auto.id));
                editAutoLink.show();
            }
        });
    }

    $('#add-item').click(function() {
        let form_idx = parseInt($('#id_form-TOTAL_FORMS').val());  // Obtén el número actual de formularios
        if (isNaN(form_idx)) {
            console.error("form_idx is NaN, check your TOTAL_FORMS field.");
            return;
        }
        console.log("Current form index:", form_idx);
        let new_form = $('#empty-form').html().replace(/__prefix__/g, form_idx);  // Reemplaza el prefijo con el índice
        $('#formset-container').append(
            '<div class="formset-row mb-3 p-3 border rounded">' +
            new_form +
            '<button type="button" class="remove-item btn btn-danger btn-sm">Eliminar</button>' +
            '</div>'
        );
        $('#id_form-TOTAL_FORMS').val(form_idx + 1);  // Incrementa el total de formularios

        // Reinitialize Select2 for new elements
        initializeSelect2($('#formset-container .formset-row:last'));
        console.log("New form added:", new_form);
    });

    $('#formset-container').on('click', '.remove-item', function() {
        $(this).closest('.formset-row').remove();

        // Recalculate the total number of forms
        let forms = $('#formset-container .formset-row');
        $('#id_form-TOTAL_FORMS').val(forms.length);
        console.log("Form removed. Total forms now:", forms.length);

        // Update the indices for each form in the formset
        forms.each(function(index) {
            $(this).find(':input').each(function() {
                let name = $(this).attr('name');
                if (name) {
                    name = name.replace(/\d+/, index);
                    $(this).attr('name', name);
                }
                let id = $(this).attr('id');
                if (id) {
                    id = id.replace(/\d+/, index);
                    $(this).attr('id', id);
                }
            });
        });
    });

    initializeSelect2();
});
</script>

<script>
function redirectToEditPage() {
    let autoId = document.getElementById('editAuto').getAttribute('data-auto-id');
    let currentUrl = encodeURIComponent(window.location.href);
    let editUrl = `/editar-auto/${autoId}/?next=${currentUrl}`;
    window.location.href = editUrl;
}

</script>

 {% endblock content %}

base/templates/orden/ordenes_entregadas.html
{% extends 'base.html' %}

{% block content %}

<h1>Órdenes Entregadas</h1>
<form method="get" action="{% url 'ordenes_entregadas' %}">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <label for="auto">Auto:</label>
                <select id="auto" name="auto" class="form-control select2">
                    <option value="">Todos</option>
                    {% for auto in autos %}
                        <option value="{{ auto.id }}" {% if request.GET.auto == auto.id|stringformat:"s" %}selected{% endif %}>
                            {{ auto }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-3">
                <label for="cliente">Cliente:</label>
                <select id="cliente" name="cliente" class="form-control select2">
                    <option value="">Todos</option>
                    {% for cliente in clientes %}
                        <option value="{{ cliente.id }}" {% if request.GET.cliente == cliente.id|stringformat:"s" %}selected{% endif %}>
                            {{ cliente }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-md-3">
                <label for="fecha_inicio">Fecha de Inicio:</label>
                <input type="date" id="fecha_inicio" name="fecha_inicio" class="form-control" value="{{ request.GET.fecha_inicio }}">
            </div>

            <div class="col-md-3">
                <label for="fecha_fin">Fecha de Fin:</label>
                <input type="date" id="fecha_fin" name="fecha_fin" class="form-control" value="{{ request.GET.fecha_fin }}">
            </div>


        </div>

        <div class="row mt-3">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Buscar</button>
                <a href="{% url 'ordenes_entregadas' %}" class="btn btn-secondary">Limpiar Filtros</a>
            </div>
        </div>
    </div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Recepcionista</th>
            <th>Técnico</th>
            <th>Vehículo</th>
            <th>Ingreso</th>
            <th>Entrega</th>

            <th>Estado de Orden</th>
            <th>Presupuesto</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for orden in ordenes %}
        <tr>
            <td>{{ orden.usuario }}</td>
            <td>{{ orden.tecnico }}</td>
            <td>{{ orden.auto }} ({{ orden.auto.cliente }})</td>
            <td>{{ orden.fecha_creacion }}</td>
            <td>{{ orden.entrega }}</td>

            <td>
                <span class="badge badge-dot">
                    <i class="bg-success"></i> {{ orden.estado }}
                </span>
            </td>
            <td>
                {% if orden.presupuesto_set.exists %}
                {% for presupuesto_item in orden.presupuesto_set.all %}
                <a href="{% url 'visualizar_presupuesto' presupuesto_item.id %}" class="text-secondary mr-2" title="Ver presupuesto">
                    <i class="feather icon-search"></i>
                </a>
                <span class="badge badge-warning">Presupuesto id: {{ presupuesto_item.id }}</span>
                {% endfor %}
                {% else %}
                <span class="badge badge-pill badge-info">Sin Presupuesto</span>
                {% endif %}
            </td>
            <td>
                <div class="dropdown">
                    <a class="btn btn-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v" style="color: black;"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'orden' orden.id %}">Visualizar</a>
                        <a class="dropdown-item" href="{% url 'editar-orden' orden.id %}">Editar</a>
                        <a class="dropdown-item" href="{% url 'eliminar-orden' orden.id %}">Eliminar</a>
                        <a class="dropdown-item" href="{% url 'historial_ordenes_auto' orden.auto.id %}">Historial</a>
                    </div>
                </div>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="9"><h3>No hay órdenes entregadas en esta lista</h3></td>
        </tr>
        {% endfor %}
    </tbody>
     <a href="{% url 'index' %}" class="btn btn-secondary">&#x1F860; Volver</a>
</table>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script>
    $(document).ready(function() {
        $('.select2').select2({
            placeholder: 'Selecciona una opción',
            allowClear: true
        });
    });
</script>

{% endblock %}